// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
  }
}

export {}
